apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cofide-credex.fullname" . }}
  labels:
    {{- include "cofide-credex.labels" . | nindent 4 }}
data:
  ENABLE_OAUTH_AS: {{ .Values.credex.enableOAuthAS | toString | quote }}
  ENABLE_SPIFFE_EXCHANGE: {{ .Values.credex.enableSPIFFEExchange | toString | quote }}
  ISSUER_URL: {{ .Values.credex.issuerURL | quote }}
  {{- with .Values.credex.accessTokenLifetime }}
  ACCESS_TOKEN_LIFETIME: {{ . | quote }}
  {{- end }}
  OAUTH_PRIVATE_KEY_FILE: {{ .Values.credex.oauthPrivateKeyFile | quote }}
  SPIFFE_ENDPOINT_SOCKET: {{ .Values.credex.spiffeEndpointSocket | quote }}
  SERVER_DEBUG: {{ .Values.credex.debug | toString | quote }}
  PORT: {{ include "cofide-credex.targetPort" . | quote }}
  {{- with .Values.credex.tls.enabled }}
  TLS_CERT_FILE: {{ $.Values.credex.tls.certFile | quote }}
  TLS_KEY_FILE: {{ $.Values.credex.tls.keyFile | quote }}
  {{- end }}
  {{- with .Values.credex.spireAgentAdminSocketHostPath }}
  SPIRE_AGENT_ADMIN_SOCKET: {{ $.Values.credex.spireAgentAdminSocket | quote }}
  {{- end }}
  {{- with .Values.credex.policyConfigFile }}
  POLICY_CONFIG_FILE: {{ . | quote }}
  {{- end }}
  {{- with .Values.credex.connectURL }}
  CONNECT_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.credex.connectTrustDomain }}
  CONNECT_TRUST_DOMAIN: {{ . | quote }}
  {{- end }}
  {{- range $i, $issuer := .Values.credex.trustedIssuers }}
  {{ printf "TRUSTED_ISSUER_%d" (add1 $i) }}: {{ $issuer.issuer | quote }}
  {{ printf "TRUSTED_ISSUER_JWKS_URL_%d" (add1 $i) }}: {{ $issuer.jwksURL | quote }}
  {{- with $issuer.allowedAudiences }}
  {{ printf "TRUSTED_ISSUER_ALLOWED_AUDIENCES_%d" (add1 $i) }}: {{ . | join "," | quote }}
  {{- end }}
  {{- end }}
{{- with .Values.credex.extraCA }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cofide-credex.fullname" $ }}-extra-ca
  labels:
    {{- include "cofide-credex.labels" $ | nindent 4 }}
data:
  ca.crt: |
    {{- . | nindent 4 }}
{{- end }}
