apiVersion: v1
kind: Service
metadata:
  name: {{ include "cofide-credex.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cofide-credex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "cofide-credex.servicePort" . }}
      targetPort: {{ include "cofide-credex.targetPort" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "cofide-credex.selectorLabels" . | nindent 4 }}
