apiVersion: v2
name: cofide-trust-zone-operator
description: Helm chart to deploy the Cofide Trust Zone Operator to a Kubernetes cluster
type: application
version: 0.1.0
appVersion: "0.1.0"

maintainers:
  - name: Cofide
    url: https://cofide.io
