{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "spiffe-webhook.labels" . | nindent 4 }}
    name: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}
