apiVersion: v1
kind: Service
metadata:
  name: {{ include "spiffe-webhook.fullname" . }} # This name is used in Certificate DNS & Webhook config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "spiffe-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https # Port name, can be referenced by targetPort
      port: {{ .Values.service.port }} # Service listens on this port (e.g., 9443)
      # targetPort should match the containerPort where the webhook application is listening
      targetPort: https-webhook # Refers to the named port 'https-webhook' in the Deployment
      protocol: TCP
  selector:
    {{- include "spiffe-webhook.selectorLabels" . | nindent 4 }}
