kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["security.istio.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
    - registry.cofide.io
    resources:
    - federatedservices
    - federatedservices/finalizers
    - federatedservices/status
    verbs: ["*"]
