kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cofide-agent-config"]
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cofide-agent-state"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
