credex:
  issuerURL: https://credex.example.org
  connectURL: https://connect.example.org
  connectTrustDomain: example.org
  # Test SPIFFE exchange feature
  enableSPIFFEExchange: true
  spireAgentAdminSocketHostPath: /run/spire/sockets/admin
  preflightChecks: false
