credex:
  issuerURL: https://credex.example.org
  connectURL: https://connect.example.org
  connectTrustDomain: example.org
  # Test TLS feature
  tls:
    enabled: true
    secretName: credex-tls
  preflightChecks: false
